branches:
  only:
  - master
language: python
python:
- '3.5'
before_script:
- if [ ${TRAVIS_BRANCH} = "master" ]; then [ -z ${GH_TOKEN} ] && exit 0; [ ${TRAVIS_PULL_REQUEST}
  = "false" ] && pip install pygithub; exit 0; fi
- if [ ${TRAVIS_BRANCH} = "master" ]; then [ -z ${GH_TOKEN} ] && exit 0; [ ${TRAVIS_PULL_REQUEST}
  = "false" ] && pip install pygithub3; exit 0; fi
script:
- if [ ${TRAVIS_BRANCH} = "master" ]; then [ -z ${GH_TOKEN} ] && exit 0; [ ${TRAVIS_PULL_REQUEST}
  = "false" ] && python3 tools/deploy.py; exit 0; fi
- python3 tools/sqf_validator.py
env:
  global:
  - secure: KH2+h0nNqef/BWLHwQuvksE8NMKE81yzdmzR6d+K8N7wPpe00tNLtFSVkgic+OReeRruLb23DOZTpJ94lctdC3QKDrgmiE83x3BbBw/KrMoUpI1qDfX5hiTybQJp5Ys41jnMyG/jIda9H4PJR2ABg0CJgrGS+cY8zGZXfsMXX709UzE7iXtKJJbQMgutU2AG8cRzc9FU28Xcx765YcM33jnbYEe/bUa8071LgCWEnC+Ena/KUjyK7lNw0LYJVaLxFObYfacHzrNb+X87WVSYeVjYQxhCzPvm/r9VTWV3EX12bG8Aoj4oSFNIIDlx+fKCCjYILrCccLxH8T5YVs6tVj+REOCT/aIvjXrII6EulTDb/tNsLQ/IckQ68jC3hSq4mTsfZGvxQz+UrwD98Exulh1O/mp45hrI8oLSCCw3tBnSxuxcYixQBSsGWNfrrU8tqRIFSLJwF3hC4z154+jrDkpbhgE1TgCkXvw9+58xg9q8bf6ORHyQjVnUtodexmmQybvea9aWyY5zGBdI0Nq9rzWkFpHyqfujUFM7e5v4fZ0ICJI6zvraMO+HpQldujJF5wD7rsLMsrn6T+MIrecNpuiJIzZpQwHzuh8YKTuYb4TNvWkb1PqWlz+/b1ET0E2K813QSSH40S1fIorr+GKcRZ/6tcx8FjMBEnRzGUbvcFw=
notifications:
  email:
    on_success: never
    on_failure: change
